spring:
  application:
    name: service--framezip-management
  data:
    mongodb:
      uri: ${MONGO_URI:token}
      database: deliverynow-db
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://keycloak-staging-alb-2122574475.us-east-1.elb.amazonaws.com/realms/filezip-dev
          jwk-set-uri: https://keycloak-staging-alb-2122574475.us-east-1.elb.amazonaws.com/realms/filezip-dev/protocol/openid-connect/certs
s3:
  bucket:
    name: filezip-bucket-service

mailersend:
  email: ${MAILER_EMAIL:token}
  token: ${MAILER_TOKEN:token}

aws:
  sqs:
    auto-create: false


jwt:
  auth:
    converter:
      resource-id: my-super-client
      principal-attribute: principal_username





