spring:
  application:
    name: service--framezip-management
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://admin:AdminPassword123@deliverynow-cluster.gg846.mongodb.net/?retryWrites=true&w=majority&appName=deliverynow-cluster}
      database: deliverynow-db
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://keycloak-staging-alb-2122574475.us-east-1.elb.amazonaws.com/realms/filezip-dev
          jwk-set-uri: https://keycloak-staging-alb-2122574475.us-east-1.elb.amazonaws.com/realms/filezip-dev/protocol/openid-connect/certs
s3:
  bucket:
    name: filezip-bucket-service

mailersend:
  email: ${MAILER_EMAIL:MS_5SU9mf@trial-7dnvo4dqpj3l5r86.mlsender.net}
  token: ${MAILER_TOKEN:mlsn.5eccb3828a63071321bc1e9468117b5c5f0f7573939821737d2c0b89865466fd}

aws:
  sqs:
    auto-create: false


jwt:
  auth:
    converter:
      resource-id: my-super-client
      principal-attribute: principal_username





