spring:
  application:
    name: service--framezip-management
  data:
    mongodb:
      uri: mongodb+srv://admin:AdminPassword123@deliverynow-cluster.gg846.mongodb.net/?retryWrites=true&w=majority&appName=deliverynow-cluster
      database: deliverynow-db
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:5000/realms/filezip-dev
          jwk-set-uri: http://localhost:5000/realms/filezip-dev/protocol/openid-connect/certs
s3:
  bucket:
    name: filezip-bucket-service

jwt:
  auth:
    converter:
      resource-id: my-super-client
      principal-attribute: principal_username





