spring:
  application:
    name: service--framezip-management
  data:
    mongodb:
      uri: ${MONGO_URI:uri}
      database: deliverynow-db
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:key}
        secret-key: ${AWS_SECRET_ACCESS_KEY:key}
        session-token: ${AWS_SESSION_TOKEN:session}
      sqs:
        endpoint: https://sqs.us-east-1.amazonaws.com/110832778598/filezip-send_email_queue

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://keycloak-staging-alb-2122574475.us-east-1.elb.amazonaws.com/realms/filezip-dev
          jwk-set-uri: https://keycloak-staging-alb-2122574475.us-east-1.elb.amazonaws.com/realms/filezip-dev/protocol/openid-connect/certs
s3:
  bucket:
    name: filezip-bucket-service

mailersend:
  email: ${MAILER_EMAIL:email}
  token: ${MAILER_TOKEN:token}

aws:
  sqs:
    auto-create: false


jwt:
  auth:
    converter:
      resource-id: my-super-client
      principal-attribute: principal_username





