apiVersion: apps/v1
kind: Deployment
metadata:
  name: filezip-management-deployment
spec:
  selector:
    matchLabels:
      app: service--filezip-management
  template:
    metadata:
      name: service--filezip-management
      labels:
        app: service--filezip-management
    spec:
      containers:
        - name: apireplicate
          image: 110832778598.dkr.ecr.us-east-1.amazonaws.com/service-filezip-management:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "800m"
              memory: "1Gi"
            requests:
              cpu: "800m"
              memory: "1Gi"